# syntax=docker/dockerfile@sha256:2780b5c3bab67f1f76c781860de469442999ed1a0d7992a5efdf2cffc0e3d769
# Partly generated by hassfest.
#
# To update, run python3 -m script.hassfest -p docker
ARG BUILD_FROM
FROM ${BUILD_FROM}

ARG BUILD_VERSION
ARG BUILD_REVISION

LABEL \
    io.hass.type="core" \
    io.hass.version="${BUILD_VERSION}" \
    org.opencontainers.image.authors="ABEDOME contributors" \
    org.opencontainers.image.description="Independent ABEDOME home automation Core distribution" \
    org.opencontainers.image.documentation="https://github.com/Mauro2020/abedome-core" \
    org.opencontainers.image.licenses="Apache-2.0" \
    org.opencontainers.image.revision="${BUILD_REVISION}" \
    org.opencontainers.image.source="https://github.com/Mauro2020/abedome-core" \
    org.opencontainers.image.title="ABEDOME Core" \
    org.opencontainers.image.url="https://github.com/Mauro2020/abedome-core" \
    org.opencontainers.image.version="${BUILD_VERSION}"

# Synchronize with homeassistant/core.py:async_stop
ENV \
    S6_SERVICES_GRACETIME=240000 \
    UV_SYSTEM_PYTHON=true \
    UV_NO_CACHE=true

WORKDIR /usr/src

# Home Assistant S6-Overlay
COPY rootfs /

# Add go2rtc binary
COPY --from=ghcr.io/alexxit/go2rtc:1.9.14@sha256:675c318b23c06fd862a61d262240c9a63436b4050d177ffc68a32710d9e05bae /usr/local/bin/go2rtc /bin/go2rtc

## Setup Home Assistant Core dependencies
COPY --parents requirements.txt homeassistant/package_constraints.txt homeassistant/
RUN \
    # Verify go2rtc can be executed
    go2rtc --version \
    # Install uv at the version pinned in the requirements file
    && pip3 install --no-cache-dir "uv==$(awk -F'==' '/^uv==/{print $2}' homeassistant/requirements.txt)" \
    && uv pip install \
        --no-build \
        -r homeassistant/requirements.txt

COPY requirements_all.txt homeassistant/
RUN \
    uv pip install \
        --no-build \
        -r homeassistant/requirements_all.txt

## Setup Home Assistant Core
# Generate English from this exact fork after its pinned requirements are ready.
COPY --parents \
    LICENSE* README* homeassistant/ pyproject.toml \
    script/__init__.py script/abedome/ script/translations/ \
    homeassistant/
WORKDIR /usr/src/homeassistant
RUN \
    python3 -m script.translations develop --all \
    && python3 script/abedome/import_backend_translations.py \
        verify --language en --language it \
    && uv pip install \
        -e . \
    && python3 -m compileall \
        homeassistant

WORKDIR /config
